# ref. https://cirrus-ci.org/examples/#flutter
container:
  image: cirrusci/flutter:latest

test_task:
  pub_cache:
    folder: ~/.pub-cache
  test_script: flutter test --coverage && bash <(curl -s https://codecov.io/bash) -c -f coverage/lcov.info
